version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.4
  - dependency-name: com.alibaba:druid
    versions:
    - 1.2.5
  - dependency-name: org.springframework.boot:spring-boot-starter-actuator
    versions:
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.4
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: org.springframework.boot:spring-boot-starter-jdbc
    versions:
    - 2.4.4
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR10
