server:
  port: 8204
spring:
  application:
    name: cloud-payment-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh_1  # 路由的id, 没有固定规则，但是要求唯一，建议配合服务名使用
#        uri: http://localhost:8201 # 匹配后提供服务的路由地址
        uri: lb://cloud-payment-service
        predicates:
            - Path=/payment/get/**  # 断言，路径相匹配的进行路由

      - id: payment_routh_2  # 路由的id, 没有固定规则，但是要求唯一，建议配合服务名使用
#        uri: http://localhost:8201 # 匹配后提供服务的路由地址
        uri: lb://cloud-payment-service
        predicates:
            - Path=/payment/getPort  # 断言，路径相匹配的进行路由
#            - After=2021-01-26T14:46:00.000+08:00[Asia/Shanghai]
#            - Before=2021-01-26T14:47:00.000+08:00[Asia/Shanghai]
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-payment

