server:
  port: 8201
  address: 127.0.0.1

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?userUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyj.cloud.beans
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

eureka:
  client:
#    # 向注册中心注册自己
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka, http://119.45.223.98:7002/eureka
  instance:
    instance-id: payment8201
    prefer-ip-address: true