server:
  port: 8301

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8888/spring_cloud?userUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyj.cloud.beans

eureka:
  client:
    # 表示是否将自己注册到EurekaServer，默认为true
    register-with-eureka: true
    # 表示是否从EurekaServer抓取已有的注册信息，默认为true. 单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: order8301
    prefer-ip-address: true