server:
  port: 8500

spring:
  application:
    name: spring-cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yjYinch/spring-cloud-config.git  # gitHub上的仓库名称
          search-paths:
            - spring-cloud-config  # 搜索目录
      label: master # 读取分支
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: spring-cloud-config-center

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

